name: CI iOS PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-latest:
    name: Check latest Godot version
    runs-on: ubuntu-latest
    outputs:
      godot_version: ${{ steps.detect.outputs.godot_version }}
    steps:
    - name: Detect latest Godot version
      id: detect
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        LATEST=$(gh api repos/godotengine/godot/releases \
          --jq '[.[] | select(.tag_name | test("^4\\.[0-9]+(\\.[0-9]+)?-stable$")) | .tag_name][0]' \
          | sed 's/-stable//')
          
        LATEST_PAD=$(echo "$LATEST" | awk -F. '{if(NF==2) print $0".0"; else print $0}')
        echo "godot_version=$LATEST_PAD" >> $GITHUB_OUTPUT

  build-and-artifact:
    name: Build & Upload Artifact
    needs: detect-latest
    runs-on: "macos-latest"

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Load .scons_cache directory
      id: ios-template-cache
      uses: actions/cache@v5
      with:
        path: ${{github.workspace}}/godot/.scons_cache/
        key: ${{github.job}}-master-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-master-${{github.ref}}-${{github.sha}}
          ${{github.job}}-master-${{github.ref}}
          ${{github.job}}-master

    - name: Set up Python 3.x
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Configuring Python packages
      run: |
        python -m pip install scons

    - name: Cache SPM dependencies
      uses: actions/cache@v5
      with:
        path: .build
        key: spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          spm-

    - name: Compiles the Source Code
      env:
        SCONS_CACHE: ${{github.workspace}}/godot/.scons_cache/
      run: |
        ./scripts/build.sh ${{ needs.detect-latest.outputs.godot_version }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: poing-godot-admob-ios-v${{ needs.detect-latest.outputs.godot_version }}-${{ github.event.pull_request.head.sha }}
        path: bin/release/*.zip
        retention-days: 14
