name: "[CD] Deploy Documentation"
on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_run:
    workflows: ['\[Manual\] Release All Platforms']
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - uses: actions/cache@v5
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material pillow cairosvg mike mkdocs-awesome-pages-plugin
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy documentation
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]] || [[ $GITHUB_EVENT_NAME == "workflow_run" ]]; then
            # Extract the version (e.g., 4.3)
            VERSION=$(grep "version=" platforms/godot_editor/addons/admob/plugin.cfg | cut -d'"' -f2 | sed 's/^v//' | cut -d. -f1,2)
            
            # Deploy versioned and stable as distinct menu entries
            mike deploy --push --update-aliases $VERSION
            mike deploy --push --update-aliases stable
            
            mike set-default --push stable
          else
            # Define the warning message for the 'latest' version.
            echo "  announcement: |" > announcement.yml
            echo "    <div class='announcement-bg-shapes'>" >> announcement.yml
            echo "      <div class='shape shape-1'>⚠️</div>" >> announcement.yml
            echo "      <div class='shape shape-2'>⚠️</div>" >> announcement.yml
            echo "      <div class='shape shape-3'>⚠️</div>" >> announcement.yml
            echo "    </div>" >> announcement.yml
            echo "    <span class='announcement-title'>⚠️ EXPERIMENTAL DOCUMENTATION</span>" >> announcement.yml
            echo "    <div class='announcement-text'>" >> announcement.yml
            echo "      You are viewing the <a href='https://github.com/poingstudios/godot-admob-plugin/tree/master' class='announcement-badge'>Master Branch</a> (latest).<br>" >> announcement.yml
            echo "      For stable releases, please see the <a href='https://poingstudios.github.io/godot-admob-plugin/stable/' class='announcement-link'>stable version</a>." >> announcement.yml
            echo "    </div>" >> announcement.yml

            # Inject the announcement right after the 'extra:' tag in mkdocs.yml
            sed -i '/extra:/r announcement.yml' mkdocs.yml
            
            mike deploy --push --update-aliases latest
          fi
