name: "[CD] Deploy Documentation (v1)"
on:
  push:
    tags:
      - 'v*-godot3'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material pillow cairosvg mike mkdocs-awesome-pages-plugin mkdocs-static-i18n
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy documentation
        run: |
          # Extract version from plugin.cfg (e.g. 1.3)
          BASE_VERSION=$(grep "version=" platforms/godot_editor/addons/admob/plugin.cfg | cut -d'"' -f2)
          CLEAN_VERSION=$(echo "$BASE_VERSION" | sed 's/^v//')
          VERSION=$(echo "$CLEAN_VERSION" | cut -d. -f1,2)
          

          # Deploy versioned folder (e.g. 1.3)
          mike deploy --push --update-aliases $VERSION
